# Generated by Django 5.2.1 on 2025-05-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotyRate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('track', 'Track'), ('playlist', 'Playlist'), ('album', 'Album')], max_length=10),
        ),
    ]
