# Generated by Django 5.2.1 on 2025-05-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpotyRate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='SpotifyUser',
        ),
    ]
