# Generated by Django 5.2.1 on 2025-05-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpotyRate', '0002_rename_user_spotifyuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifyuser',
            name='created_at',
        ),
    ]
