# Generated by Django 5.2.1 on 2025-05-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotyRate', '0004_remove_spotifyuser_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
