# Generated by Django 5.2.1 on 2025-05-16 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotyRate', '0005_spotifyuser_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='SpotyRate.media'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'media'), name='unique_user_media_rating'),
        ),
    ]
